### ISSUE TITLE
variable name issue

### ISSUE THREAD

**Issue by SUREYAPRAGAASH09** [UdhaikumarMohan/Hacker-Rank#1]
next time when you write program in any language, 

1. please make that you provide a **valid variable name** that correctly suits to the context for the problem
2. As you working in python language, please make sure you provide **proper indentation**  before uploading in this platform
3. If you can provide, your approach means how you arrived the mathematical solution, it is highly appreciable. 
4. remove some extra space

**Comment by UdhaikumarMohan** [comment]
Points Taken, Thank you for your valuable inputs
